# searchSpaceFile: search_space.json

searchSpace:
  sigma:
    _type: choice
    _value: [0.00001, 0.0001, 0.001, 0.01, 0.1]
  lambda_A:
    _type: choice
    _value: [0.0001, 0.001, 0.01, 0.1, 1.00001]
  lambda_B:
    _type: choice
    _value: [0.001, 0.0001, 0.00001, 0.000001, 0.0000001, 0.00000001, 0.0000000001]
  # learning_rate:
  #   _type: choice
  #   _value: [0.00001, 0.0001, 0.001, 0.01]

trialCommand: python3 parameter_tune.py --dataset poker --T 30 --n 1000 --p 1200 --sigma 0.01
trialGpuNumber: 1
trialConcurrency: 8
maxTrialNumber: 50
# tuner:
#   name: TPE
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:  # For other platforms, check mnist-pytorch example
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: true  # NOTE: Use "true" if you are using an OS with graphical interface (e.g. Windows 10, Ubuntu desktop)
                       # Check the doc for details: https://nni.readthedocs.io/en/latest/reference/experiment_config.html#useactivegpu